version: '3'
services:
  math:
    build:
      context: ./math
      dockerfile: Dockerfile

  string:
    build:
      context: ./string
      dockerfile: Dockerfile

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - 8080:8080